version: "3"

services:

  nginx:
    image: "jwilder/nginx-proxy"
    volumes:
      - "./data/certs:/etc/nginx/certs"
      - "./data/vhost.d:/etc/nginx/vhost.d"
      - "./data/html:/usr/share/nginx/html"
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
    ports:
      - "80:80"
      - "443:443"
    networks:
      - proxy

  letsencrypt:
    image: "jrcs/letsencrypt-nginx-proxy-companion"
    volumes_from:
      - "nginx-proxy"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    environment:
      - DEFAULT_EMAIL=sabyrbayev.adi32@gmail.com

networks:
  proxy:
    external:
      name: nginx-proxy
