version: "3"

services:
  nginx-proxy:
    image: "jwilder/nginx-proxy"
    container_name: nginx-proxy
    volumes:
      - "certs:/etc/nginx/certs"
      - "vhost:/etc/nginx/vhost.d"
      - "html:/usr/share/nginx/html"
      - "./data/conf.d:/etc/nginx/conf.d"
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
    restart: always
    ports:
      - "80:80"
      - "443:443"
    networks:
      - https

  letsencrypt:
    container_name: letsencrypt
    image: "jrcs/letsencrypt-nginx-proxy-companion"
    volumes_from:
      - nginx-proxy
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    restart: always
    environment:
      DEFAULT_EMAIL: ${DEFAULT_EMAIL}

volumes:
  vhost:
  html:
  certs:

networks:
  https:
    external:
      name: ${HTTPS_NETWORK}
